### ISSUE TITLE
i18n request

### ISSUE THREAD

**Issue by aixcyi** [csense-oss/idea-kotlin-not-highlighter#7]
This plugin currently works well, and providing internationalized text will make it more popular I think.

My native language is Chinese and I would very much like to contribute to this project of internationalization.

It seems to helpful for first step in i18n: https://plugins.jetbrains.com/docs/intellij/internationalization.html

**Comment by Tvede-dk** [comment]
Hi, 
Thanks for the interrest :) 
What part(s) are you thinking of?
If you are thinking of the code / comment names, then (sorry, I forgot to document it :( ), I have actually added the ability to specify your "own" negation words, in a file named (placed at the root of the project)
```
.namesToHighlight
``` 
with one word on each line, like so
```
Test
```

resulting in
![image](https://github.com/user-attachments/assets/0935867e-6cb2-4fbf-b770-1457d78d44fa)

**Comment by aixcyi** [comment]
Oh, sorry for missing adequate description. I means text on settings, in other words user interface.

![图片](https://github.com/user-attachments/assets/ddf9a7ae-b484-4558-bd30-74388723d1dc)

**Comment by aixcyi** [comment]
Thx :)

**Comment by Tvede-dk** [comment]
@aixcyi You are welcome :) however, due to the shared lib not being released yet,you might not be able to build it. If you want me to include the translations you come up, either just make a pr or let me know. Just glad you liked the plugin :)

**Comment by aixcyi** [comment]
Thanks to the small amount of text, I think it is possible to ensure translation accuracy manually, therefore, we can temporarily ignore problem that the plugin cannot build.

After all text that needs to be translated was extracted into a message bundle, i would be happy to translate them asap.

\>w<
